Hw-5 Add api, redux, thunk
cafecco/react-project pull request #3
Opened 2020-09-20 22:28 UTC by cafecco

2020-09-21 14:48 UTC, AnonJedi requested changes

2020-09-21 14:48 UTC, AnonJedi commented on src/components/common/Input/Input.jsx
> +    return <div className="CustomInput">
оттформатируй это, пожалуйста

2020-09-21 15:28 UTC, AnonJedi requested changes

2020-09-21 15:28 UTC, AnonJedi commented on src/store/actionCreator/moviesAC.js
> +import moviesAction from "../actionNames/moviesAction";
а почему сразу в index не писать это всё? немного запутанно получается

2020-09-21 15:28 UTC, AnonJedi commented on src/store/actionNames/index.js
> +export default {...moviesAction};
то же самое, почему сразу не в index?

2020-09-21 15:28 UTC, AnonJedi commented on src/store/actionNames/moviesAction.js
> +const GET_MOVIES_START = 'GET_MOVIES_START';
можно сразу экспортить константы
```javascript
export const GET_MOVIES_START = 'GET_MOVIES_START';
```

2020-09-21 15:28 UTC, AnonJedi commented on src/store/reducers/moviesReducer.js
> +import ACTIONS from '../actionNames/index';
в js если ты хочешь что то импортить из index, то можно его не указывать, движок по дефолту ищет файл с именем index
```javascript
import ACTIONS from '../actionNames';
```

2020-09-21 15:28 UTC, AnonJedi commented on src/thunk/movies-thunk.js
> +import { sortByFieldFunc } from "../functions/sortByFiledFunc";
вообще такие экшоны сразу со всеми остальными пишут

2020-09-22 11:24 UTC, cafecco commented on src/components/App/App.jsx
> +        dispatch(getAllMovies());
будет исправлено в роутинге)

2020-09-27 17:46 UTC, merged